spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33060/self_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      capital-mode: true

logging:
  level:
    com.baomidou.samples: debug